# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      
    - name: yarn package installation ⏳
      run: yarn install
      working-directory: ./backend/lambda/generator     
      
    - name: Run Tests 🧪
      run: yarn test
      working-directory: ./backend/lambda/generator
      
    - name: install serverless
      run: sudo npm i -g serverless
      
    - name: serverless deploy 
      run: serverless deploy --stage prod
      working-directory: ./backend/lambda/generator  
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
  deployFrontend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./gh-pages
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v1

    - name: Installation ⏳
      run: yarn
      working-directory: ${{env.working-directory}}
   
    - name: Build 🧱
      run: yarn build
      working-directory: ${{env.working-directory}}
    
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3      
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: gh-pages/build
